name: benchmarks
on:
  push:
    branches:
      - main

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: 1.15.x
      - uses: actions/checkout@v2
      - name: Run benchmark
        run: go test -bench 'BenchmarkNew' | tee output.txt
