name: benchmarks
on:
  push:
    branches:
      - main

jobs:
  benchmark:
    name: Run Go benchmark example
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
      - name: Run benchmark
        run: go test -bench 'BenchmarkNew' | tee output.txt
