name: tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.41.1

  test:
    needs: lint
    strategy:
      matrix:
        go: [1.15.x, 1.16.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      - uses: actions/checkout@v2
      - run: go test -race -covermode atomic -coverprofile=covprofile ./...
      - name: Install goveralls
        if: runner.os == 'Linux'
        run: go get github.com/mattn/goveralls
      - name: Send coverage
        if: runner.os == 'Linux'
        run: goveralls -parallel -coverprofile=covprofile -service=github -flagname=${{ runner.os }}-Go-${{ matrix.go }}

  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: tip
      - uses: actions/checkout@v2
      - name: Install goveralls
        run: go get github.com/mattn/goveralls
      - name: Send coverage
        run: goveralls -parallel-finish -service=github
