name: strings/bexp

concurrency:
  group: strings/bexp-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [ main ]
    paths:
      - "strings/bexp/**"
      - ".github/workflows/strings-bexp.yaml"

defaults:
  run:
    working-directory: ./strings/bexp

jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.21.5'
      - name: Run tests and generate coverage report
        run: |
          go test -race  -coverpkg=./... -coverprofile=coverage.out ./...
