name: tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        version: ['>=1.18.0', 'latest']
        platform: [ubuntu-22.04, macOS-12, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v3
      - name: golangci-lint
        if: runner.os == 'Linux'
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.50
      - name: Run tests
        run: |
          go test -v -race -covermode atomic -coverprofile=covprofile ./...
      - uses: shogo82148/actions-goveralls@v1
        if: runner.os == 'Linux'
        with:
          path-to-profile: covprofile
